version: "3"
services:
    app:
        build: .
        container_name: container-edclone-app
        # command: bash -c "npm install && npm i -g @adonisjs/cli && adonis serve --dev"
        ports:
            - "3000:3333"
        volumes:
            - .:/home/node/app
        # depends:
        #     - db

    db:
        build: ./database
        container_name: container-edclone-db
        volumes:
            - "./database/db:/var/lib/mysql"
        restart: always
        ports:
          - "3306:3306"

        environment:
          - MYSQL_ROOT_PASSWORD:"edclone"
          - MYSQL_DATABASE:"edclone"

    phpmyadmin:
        container_name: container-edclone-phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1.3
        #5.1.3 / 8.0.15
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
        # depends:
        #     - db

    redis-compose:
        image: redis:alpine
        # command: redis-server
        command: redis-server --requirepass redis --appendonly no
        container_name: "background-job"
        # hostname: redis
        ports:
          - "6379:6379"
        healthcheck:
          test: ['CMD', 'redis-cli', 'ping']
            # volumes:
            #   - /home/duducp/Redis:/var/lib/postgresql/data
