version: "3"
services: 
    app:
        build: .
        container_name: container-edclone
        command: bash -c "npm install && npm i -g @adonisjs/cli && adonis serve --dev"
        ports:
            - "3333:3333"
        volumes: 
            - .:/home/node/app

    db:
        build: ./database
        volumes:
            - "./database/db:/var/lib/mysql"
        restart: always
        ports:
          - "3306:3306"
         
        environment:
          - MYSQL_ROOT_PASSWORD:"edclone"
          - MYSQL_DATABASE:"edclone"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1

    
    